# Generated by Django 3.1.3 on 2021-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='createDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
