# Generated by Django 3.1.3 on 2021-08-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBoard', '0003_auto_20210801_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='createDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='createDate',
            new_name='date',
        ),
    ]
